FROM node:14.15-alpine AS staging

# USER node
RUN mkdir /home/node/app
WORKDIR /home/node/app

COPY app/package.json ./
RUN yarn
COPY app .
RUN yarn build

FROM nginx:1.21.3-alpine

RUN apk --no-cache add curl

COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=staging /home/node/app/build /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]

